[package]
name = "tecdsa"
version = "0.0.3"
description = "Generate and manage tECDSA identities"
repository = "https://github.com/bittoko/tecdsa"
keywords = [ "ecdsa", "identities", "signature", "crypto", "threshold", "tecdsa" ]
license = "MIT"

[dependencies]
test = "1.2.0"
sha2 = "0.0.4"
base = "0.10.4"
utilities = "1.0.0"
stable-buffer = "1.0.1"

[toolchain]
moc = "0.10.4"
